# Generated by Django 4.2.4 on 2024-07-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('category', '0002_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.categoryoffer'),
        ),
    ]
