# Generated by Django 4.2.4 on 2023-11-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
