# Generated by Django 4.2.4 on 2023-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
