# Generated by Django 4.2.4 on 2023-11-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variation_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='discounted_price',
        ),
    ]
