# Generated by Django 4.2.4 on 2023-11-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_variation_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
