# Generated by Django 4.2.7 on 2023-11-07 23:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddress',
            new_name='UserAddressBook',
        ),
    ]
