# Generated by Django 4.2.7 on 2023-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_rename_useraddress_useraddressbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='address_line_1',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
