# Generated by Django 4.2.4 on 2024-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_otp_created_account_otp_expiry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
