# Generated by Django 4.2.4 on 2023-11-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='transaction_id',
        ),
    ]
