# Generated by Django 4.2.4 on 2023-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_payment_is_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_refunded',
        ),
        migrations.AddField(
            model_name='order',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
