# Generated by Django 4.2.4 on 2024-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_user_id_wallet_user_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='New', max_length=10),
        ),
    ]
